### ISSUE TITLE
번역기 번역을 조금씩 수정하며 게임중인데요

### ISSUE THREAD

**Issue by Ellencia** [son2688s/SPT-Korean-Patcher#1]
공유하고 싶으면 여기다 올려도 되나요?

**Comment by gomeng-dev** [comment]
네 그렇게 하셔도 됩니다 다만 반영은 본업이 심히 바쁜지라 언제될지 모름,,,

**Comment by Ellencia** [comment]
그럼 일단 오늘까지 번역한 것 올릴게요 
의역이 많이 들어가긴 했는데, 이전 번역이랑 말투를 통일시키려고 했고
퀘스트 영어이름도 넣어서 위키에 검색하기 조금은 편해질겁니다.
안된 것도 아직 많긴 하지만요
[kr.json](https://github.com/user-attachments/files/15528837/kr.json)

**Comment by gomeng-dev** [comment]
금일 업로드 합니다, 고생 많으셨어요 감사합니다!

**Comment by Ellencia** [comment]
[kr.json](https://github.com/user-attachments/files/15831564/kr.json)
계속 수정한 ㄱ것 업데이트 입니다.

**Comment by gomeng-dev** [comment]
금일 SPT hub에 업데이트 할게요. 깃에만 올리고 hub엔 안올렸었네요; 고생하셨습니다
